##Azure Kubernetes service with Container registry
replicaCount: 1

image:
  repository: springdemoacr.azurecr.io/my-spring-boot-app
  tag: 0.4
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080
env:
  JAVA_OPTS: >-
    -Xms512m
    -Xmx1024m
    -XX:+UseG1GC
    -Dspring.profiles.active=prod
    -Duser.timezone=UTC


###Azure Kubernetes service with docker image
#replicaCount: 1
#
#image:
#  repository: rama534s/my-spring-boot-app
#  tag: 0.4
#  pullPolicy: Always
#
#service:
#  type: LoadBalancer
#  port: 80
#  targetPort: 8080

##local....
#replicaCount: 1
#
#image:
#  repository: my-spring-boot-app
#  tag: 0.1
#  pullPolicy: Never  # Change to IfNotPresent or Always if needed
#
#service:
#  type: NodePort
#  nodePort: 30080
