name: Build and Push Docker Image to ACR with Username/Password

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: springapp 
  ACR_LOGIN_SERVER: springdemoacr.azurecr.io
  HELM_RELEASE_NAME: springapp-release
  HELM_CHART_PATH: ./charts/springapp

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Generate Timestamp Tag
        id: image_tag
        run: echo "tag=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT

      - name: Decode and Set Kubeconfig
        run: |
            echo "${{ secrets.KUBECONFIG_B64 }}" | base64 -d > kubeconfig
            export KUBECONFIG=$(pwd)/kubeconfig

      - name: Login to ACR using username and password
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_LOGIN_SERVER }} \
            --username ${{ secrets.ACR_USERNAME }} \
            --password-stdin

      - name: Build spring app
        run: mvn clean install -DskipTests

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Tag Docker image for ACR
        run: docker tag $IMAGE_NAME:$IMAGE_TAG ${{ secrets.ACR_LOGIN_SERVER }}/$IMAGE_NAME:$IMAGE_TAG

      - name: Push Docker image to ACR
        run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/$IMAGE_NAME:$IMAGE_TAG

      - name: Install Helm
        run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Deploy Helm Chart to AKS
        run: |
          export KUBECONFIG=$(pwd)/kubeconfig
          helm upgrade --install $HELM_RELEASE_NAME $HELM_CHART_PATH \
            --set image.repository=$ACR_LOGIN_SERVER/$IMAGE_NAME \
            --set image.tag=${{ steps.image_tag.outputs.tag }}
